### ISSUE TITLE
Update to Blender 2.8

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace-todo#10]

**Comment by fjbagley** [comment]
Here is what ST has so far for basics campaign and beginner mini projects: https://studiotyee.sd72.bc.ca/maps/18/9/20/

Intermediate campaign and mini projects:
https://studiotyee.sd72.bc.ca/maps/40/

After that is a work in progress

**Comment by tylerecouture** [comment]
I've cloned Studio Tyee new basics campaign (thanks @fjbagley !) and I'm tweaking/updating them a bit.  Finished thru to 
Blender Basics 4. Materials & Rendering 
https://hackerspace.sd72.bc.ca/quests/1587/

**Comment by tylerecouture** [comment]
List of Updates I made going through parts 1-10 of the Campaign
- Redid the [0. Intro](https://hackerspace.sd72.bc.ca/quests/1593/) and pulled out first 2 mins of first video for it
- Updated the test in [2. Navigating 3D](https://hackerspace.sd72.bc.ca/quests/1584/) to include some new things covered in the new video, also reordered to match the order they are presented
- [6. Edit Mode](https://hackerspace.sd72.bc.ca/quests/1588/) - I pulled out the loop cut stuff into its [own quest](https://hackerspace.sd72.bc.ca/quests/1595/) as I think for newcomers edit mode is overwhelming enough
-8. [3D Text](https://hackerspace.sd72.bc.ca/quests/1592/) moved up (mostly so they could include 3D text in front of their models from now on
-Combined the Bevel and Inset faces quests into one.
- Made the house the Campaign final project and [10th quest](https://hackerspace.sd72.bc.ca/quests/1591/).

Among many other tweaks (The original campaign was very old, so cleaned up the formatting, clarified instructions everywhere, renumbered them, etc.)

**Comment by fjbagley** [comment]
Good updates. I have copied them over to ST. Fixed a couple of errors on HS as you had Blender listed as 3.8 (unless you have a secret beta from 2022) in 0. Intro.

**Comment by tylerecouture** [comment]
Complete Blender Basics Part 2.  Similarly, I took the opportunity to update a lot of stuff.  It's quite a bit different now, basically all explained in the [Intro here](https://hackerspace.sd72.bc.ca/quests/1638/) and has an awesome [project at the end](https://hackerspace.sd72.bc.ca/quests/1574/) that requires all 5 concepts.

I'm going move your additional animation quests until after the Blue Belt.  The idea is that by Blue Belt they are familiar with pretty much everything, and can now dig deeper into areas of their choosing.
