### ISSUE TITLE
Add more game playing to History of Video Games campaign

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace-todo#143]
- [ ] for quest #9:  https://hackerspace.bytedeck.com/quests/submission/92504/
https://www.playemulator.com/snes-online/mortal-kombat-3/  "I would say to pass the assignment you need to beat the first fighter, after that it becomes super hard to land any hits. "

- [ ] quest #10: ?

**Comment by fjbagley** [comment]
Gran Turismo? 
http://www.ps1fun.com/gran-turismo

It is the best selling PlayStation game of all time and there hasn't been a racing game yet.

**Comment by tylerecouture** [comment]
Good idea.  I also want to make part 2 of this series focused on History of PC gaming, as there are a lot more videos in the playlist!  My students love this campaign.

**Comment by fjbagley** [comment]
History of PC gaming sounds good great! I had a couple of students give Gran Turismo a go and [updated our quest ](https://studiotyee.bytedeck.com/quests/1521/)with what we think is a fair challenge. A gamer who plays racing games regularly beat it first time, but it took a couple of tries for another student.

**Comment by tylerecouture** [comment]
I added gran tourismo, thanks for that one!  The controls weren't accurate to defaults my students were seeing so I updated them to be more clear (one student couldn't figure out how to even start the game)
https://hackerspace.bytedeck.com/quests/1517/

**Comment by tylerecouture** [comment]
I think we're out of luck for Quest #10 as there aren't any online emulators for the XBox or GameCube.
