### ISSUE TITLE
Update Pyfiddle Links

### ISSUE THREAD

**Issue by fjbagley** [timberline-secondary/hackerspace-todo#146]
pyfiddle.io no longer exists. There is an equivalent called http://pythonfiddle.com/. I will be updating all my quests accordingly. Do you want me to do the same to Hackerspace?

**Comment by fjbagley** [comment]
This isn't secure of course, but pyfiddle.io wasn't either.

Also, the save feature relies on a Google or Facebook account

**Comment by tylerecouture** [comment]
Maybe we should just remove any reference to fiddles.

**Comment by fjbagley** [comment]
What would we replace it with?

**Comment by tylerecouture** [comment]
What quest is this for?  I don't think it needs any replacement, just remove it.

**Comment by fjbagley** [comment]
About 10 python quests. Users will still need an IDE. Are you using Py Charm anymore?

**Comment by tylerecouture** [comment]
They all use IDLE, the python shell directly from the terminal, or visual
studio code.

**Comment by fjbagley** [comment]
Fiddle references removed ST and HS.
