### ISSUE TITLE
New Badge: Published Artist

### ISSUE THREAD

**Issue by fjbagley** [timberline-secondary/hackerspace-todo#148]
I have been trying to encourage my student to build a portfolio. I added the [Published Artist](https://studiotyee.bytedeck.com/achievements/141) badge. I didn't see an equivalent on Hackerspace. May or may not be useful for you.

**Comment by fjbagley** [comment]
Luckily the png looks a little nicer when awarded and in badge view.

**Comment by tylerecouture** [comment]
Great idea!
