### ISSUE TITLE
How AI Works by Code.org

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace-todo#149]
https://www.youtube.com/playlist?list=PLzdnOPI1iJNeehd1RXhnVMBFi1WhWLx_Y

**Comment by tylerecouture** [comment]
@fjbagley 
I tacked it on the the end of the "How Computers Work" mini campaign:
https://hackerspace.bytedeck.com/maps/36/

**Comment by fjbagley** [comment]
Sweet! I have added now. Good spot to put it as the How Computers Work are a good foundation for AI. Thanks.
