### ISSUE TITLE
Simplify Intro Quests?

### ISSUE THREAD

**Issue by fjbagley** [timberline-secondary/hackerspace-todo#151]
I have a portion of my class that just skips straight to the videos and only read submission instructions. There is often key information missed that would actually save them time.

This behaviour in part is influenced by the very first quests. Quest descriptions aren't that long for capable readers, but those that struggle learn that they can skip much of the text in the quest descriptions and go straight to the video/submission instructions.

What are your thoughts on simplifying the very intro quests? Students would perhaps be more likely to fully read them and build the habit of reading the quests.

**Comment by tylerecouture** [comment]
Yep, they almost all need to be revamped. I think most of those still look
mostly the same from when I first started this 6 years ago from when I had
no idea what I was doing.

So important to set good habits and expectation right at the beginning.

Just hard to get to because I really enjoy making new content....revising
old content seems like work...haha!

**Comment by fjbagley** [comment]
I have updated my create an avatar quest: https://studiotyee.bytedeck.com/quests/3/. I removed your awesome facts about avatars :( and updated the site to avatarmaker.com avoid Flash. You can download the files from this site, but I think having students practice taking a screenshot is still valuable. I also removed the link from the submission instructions forcing students to at least skim the quest details to get there.

**Comment by tylerecouture** [comment]
Thanks for this!  I updated mine too based on your suggestions.  I'm gonna use the download since I have an Orientation quest dedicated to screenshots (which also needs updating...)

**Comment by tylerecouture** [comment]
For tracking which quests have been reviewed/updated:
- [x] Welcome (AG new video, Sept 2021)
- [x] How XP Works (AG new video, Sept 2021)
- [x] DELETED: How do I get to the Good Stuff (deleted Sept 2021)
- [x] Create an Avatar
- [x] Who owns your creations (is this quest necessary? Maybe remove this one...) (Avi G likes this one! Instructions have been cleaned up and submissions are better)
- [x] Class Contract (Avi G thinks this is fine as is)
- [x] Ubuntu Intro --> Break into 2 quests:
   - [x] How to Screenshot and Screencast
   - [x] How to Linux/Ubuntu

**Comment by tylerecouture** [comment]
Linux/Ubuntu: https://hackerspace.bytedeck.com/quests/689/

**Comment by tylerecouture** [comment]
Screenshots: https://hackerspace.bytedeck.com/quests/1736/

**Comment by mizzgoldberg** [comment]
Update November 2021: How to Linux - I temporarily removed some parts; quest is too long. Needs further review. https://hackerspace.bytedeck.com/quests/1735/

**Comment by fjbagley** [comment]
I simplified the XP intro quests even more. I have taken the How is XP Determined section from seven bullet points and a table to this:

- Generally, quest XP is based on how long the quest should take an average student who follows the quests instructions carefully.
- Most students that work hard (with few distractions) for a 2.5 hour class should be able to complete enough quests to earn 20-25 XP. 

Most students aren't reading this section and I believe it is just creating bad habits from day one.

**Comment by tylerecouture** [comment]
@fjbagley much needed simplification, I just made similar changes to ours.

Those details are captured here: 
https://hackerspace.bytedeck.com/pages/FAQ/quest-style-guide/

**Comment by fjbagley** [comment]
I added most of your quest style guide to the wiki: [quest creation](https://github.com/bytedeck/bytedeck/wiki/Quest-Creation)

**Comment by fjbagley** [comment]
There is a fair bit of redundancy in the class contract. I was able to combine paragraphs (internet use and vandalism for example) and remove a few sentences. The entire thing now fits in one page even with our full food and drink policy. Perhaps it is closer to being readable by a grade 9? 

Studio Tyee [Class Contract](https://studiotyee.bytedeck.com/quests/2/) quest

**Comment by tylerecouture** [comment]
Thanks @fjbagley, I tweaked our contract with your suggestions.  I think that covers this issue as we've reviewed every orientation quest at least once at this point. Thanks!
