### ISSUE TITLE
Inkscape Heart/Hatch should be 6 XP

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace-todo#162]
https://hackerspace.bytedeck.com/quests/submission/97277/

Or just retire it or replace with better Nick Saporito...

**Comment by tylerecouture** [comment]
Also, there are two options for the project, need to mention both or provide sample for both.

**Comment by fjbagley** [comment]
Not the most exciting project, but I like the switch up to text presentation. Videos are great, but sometimes reading is good too :)

**Comment by tylerecouture** [comment]
Do you have them do both the sketchy heart and the dots to dots one?

**Comment by fjbagley** [comment]
Usually both. I didn't have access to the archived quest last year, so it wasn't working. Thanks for finding the archive link!

**Comment by tylerecouture** [comment]
Removed old links and updated for clarity to complete both designs
