### ISSUE TITLE
Blender Sculpting and 3D Printing a Wolf

### ISSUE THREAD

**Issue by fjbagley** [timberline-secondary/hackerspace-todo#168]
Disappointed it is a wolf and not a fish, but a good 3 part series none the less that goes through sculpting, slicing and printing. [Part one](https://studiotyee.bytedeck.com/quests/1836/) is up. Might need to be 15XP because sculpting takes additional time.

**Comment by fjbagley** [comment]
Part 2 is up. Part 3 is almost done. Just missing a Cura slicing tutorial. Do you have a good one?

**Comment by tylerecouture** [comment]
I did have start a 4 part series...but never used it, it might be way out of date now? Take a look:
https://hackerspace.bytedeck.com/quests/962/ (you can link back through the requirements)

**Comment by fjbagley** [comment]
I forgot that Grant Abbitt had a Cura slicing tutorial that goes along with this series. I have added part 4 to the series. I only have new Blender students this rotation, so may have to wait until the end of the rotation to get one to test this mini series. If you have an interested student, then feel free to give it a go :)

**Comment by tylerecouture** [comment]
I'm on my Prep so I won't have anyone till next rotation.

**Comment by fjbagley** [comment]
There might be a good new Blender student for the job in my class.

**Comment by fjbagley** [comment]
I have had two students try the quest line. Both said sculpting is very hard even with the tablets and became frustrated. He makes it look so easy! 

Sculpting seems like a great skill to have, so I will look at finding a more beginner video on sculpting and introduce this quest line at a higher level.

Video is in this space for the rest of the year. Feel free to have an advanced students give it a go over then next couple of rotations.
