### ISSUE TITLE
Crypto campaign

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace-todo#169]
Well... seems like this is obvious now, and what a cool thing to teach when we can cap it off with having student create their own miner!  I'm just gonna throw down some ideas here.

Would love to fine some very beginner stuff/explainers to start out with.

Best Blockchain explainer I've seen (still pretty advanced, but...): 
https://www.youtube.com/watch?v=bBC-nXj3Ng4&vl=en

How hard is it to find a 256-bit hash just by guessing and checking?:
https://www.youtube.com/watch?v=S9JGmA5_unY&t=0s

I started a question (randomly picked #3...)
https://hackerspace.bytedeck.com/quests/1761/

Make your own blockchain and crypto currency in Python from scratch  (starts at about 1:07? but maybe later still, the beginning is intro to Python):
https://www.youtube.com/watch?v=KARxDX5DTgY

**Comment by tylerecouture** [comment]
I'm working on this now, my students want in! 

Throwing some more ideas in (vids and channels)
BLockchain:
https://www.youtube.com/watch?v=SSo_EIwHSd4
https://www.youtube.com/watch?v=aQWflNQuP_o
https://www.youtube.com/watch?v=2yJqjTiwpxM

Intro Quest?
https://www.youtube.com/watch?v=Nxy7p0jlu7Y
https://www.youtube.com/watch?v=s4g1XFU8Gto

**Comment by tylerecouture** [comment]
@fjbagley let me know if you have any ideas or comments, rough sketch:

This seems too long, might be worthwhile to break it into two campaigns, with the first focusing on the basics and bitcoin, and the second expanding into more complicated topics like Ethereum, smart contracts, defi, etc?

1. Introduction (this quest)
2. What is Bitcoin?
3. How does Bitcoin work?
4. What does it mean to "have" a bitcoin?
5. Mining
6. Cryptocurrency Wallets
7. Getting and Using a Wallet
8. The Lightning Network
9. What is Ethereum?
10. What is DeFi?
11. Programmable Money
12. Smart Contracts
13. What are Forks?
14. Proof of Work
15. Proof of Stake
16. Custody and Hardware Wallets

**Comment by tylerecouture** [comment]
https://www.youtube.com/watch?v=W15A7Lf0_fI

**Comment by tylerecouture** [comment]
https://hackerspace.bytedeck.com/maps/37/
First:
https://hackerspace.bytedeck.com/quests/1777/
Last:
https://hackerspace.bytedeck.com/quests/1785/

**Comment by fjbagley** [comment]
Thanks for making these quests, Tylere. How do you send the students the sats? I assume you aren't using layer 1.

**Comment by tylerecouture** [comment]
Ya we do use layer one for this first one.  I use Blue wallet (same as students set up in quest 9)  I just put some sats in a hackerspace wallet address.  Setting the fees to low it ends up being 15 cents or so.  I plan to get into Lightning network and doing some layer 2 stuff (also supported by the Blue wallet) but haven't got to it.  Also Ethereum

**Comment by fjbagley** [comment]
15 cents isn't bad. I'd be charged $1.50 to eTransfer using Interac. I'm used to ETH where layer 1 is usually $5-$15 for sending!
