### ISSUE TITLE
Portfolio quest

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace-todo#183]
XP too high and it's not good cus currently students submit it with 3 cookie-cutter projects.

Related to #1 and #148 

https://hackerspace.bytedeck.com/quests/submission/100522/

**Comment by fjbagley** [comment]
I added this as a quest. I went with 5XP plus 2 for the badge. ST now has an update you portfolio quest (pretty much a duplicate of the create a portfolio quest) which is 3 XP and repeatable once per semester with the journeyman rank as a prerequisite.

**Comment by tylerecouture** [comment]
Thanks for this! I updated mine to match, though I combined the two into a single quest and made repeatable by semester, and upped the prereq to Digital Journeyman (595 XP)
