### ISSUE TITLE
Age of Asparagus Videos Missing

### ISSUE THREAD

**Issue by fjbagley** [timberline-secondary/hackerspace-todo#187]
A number of YouTuber Age of Asparagus videos are no longer available. Items of note are:

Blender Animate Initials
GIMP Intro

Did they get removed for a reason?

**Comment by tylerecouture** [comment]
Can you provide the links?  YouTube auto-converted some old videos I has made to private, I thought I switched them all back but must have missed some.

**Comment by tylerecouture** [comment]
Might be fixed now.  Close if it is, provide links if it isn't. THanks!

**Comment by fjbagley** [comment]
The ones I noticed are fixed. Thanks!
