### ISSUE TITLE
Broken sample links

### ISSUE THREAD

**Issue by mizzgoldberg** [timberline-secondary/hackerspace-todo#190]
Two quests with broken sample links in instructor notes. Access denied.
https://hackerspace.bytedeck.com/quests/1636/
https://hackerspace.bytedeck.com/quests/1610/

**Comment by mizzgoldberg** [comment]
can this student example be used as the sample? https://hackerspace.bytedeck.com/quests/submission/109137/

**Comment by tylerecouture** [comment]
Fixed, thanks!
