### ISSUE TITLE
Blender beginner mini projects need more info

### ISSUE THREAD

**Issue by mizzgoldberg** [timberline-secondary/hackerspace-todo#195]
https://hackerspace.bytedeck.com/quests/submission/107791/
No information on how to find rendered animation. Applicable to several quests in the Blender Beginner Mini Projects campaign. Maybe need just a line of text, or a short video, or ?
https://hackerspace.bytedeck.com/maps/49/15/22/

**Comment by tylerecouture** [comment]
I added a video-rendering tutorial to one of the animation quests, and made the other animations require it.  However, I added them in a chain to keep the map tidy, even though ideally we would have them all available after the Animation intro

![image](https://user-images.githubusercontent.com/10604391/143934810-31907475-d396-4455-a002-7cc9570e855e.png)
