### ISSUE TITLE
Add First Nations Art to Elements of Art and Design

### ISSUE THREAD

**Issue by fjbagley** [timberline-secondary/hackerspace-todo#198]
An easy way to bring additional first nations culture into our quests. We already have some for each of the new quests in the later campaign, but could add some for the earlier ones. 

@mizzgoldberg, what are your thoughts on these? 

Line: 
Smudge by the Lake, Pam Cailloux (Metis in Quebec)
![image](https://user-images.githubusercontent.com/37415548/145899066-c3b891c5-89e4-4d12-b339-0bfb503bdb28.png)

Colour:
Dzunukwa, Rane Cook (born in Alert Bay)
![image](https://cedarhilllonghouse.ca/wp-content/uploads/2019/01/Rande-Cook-Dzunukwa-scaled.jpg)

Space:
Kitasoo Dawn, Roy Henry Vickers (has gallery in Tofino)
![image](https://image.invaluable.com/housePhotos/maynardsfineart/17/634317/H0759-L156325151.jpg)

**Comment by fjbagley** [comment]
I updated the [line ](https://studiotyee.bytedeck.com/quests/1053/)and [space ](https://studiotyee.bytedeck.com/quests/1043/) quests, but skipped the colour as Fly Gurl falls within the first nations category (not that we should limit ourselves to just one).

**Comment by tylerecouture** [comment]
Thanks! I updated ours too.
