### ISSUE TITLE
Replace Intro 2D Platformer Game

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace-todo#200]
It's old version of Godot, things have changed quite a bit, and the Autotiles section is particularily painful, and already covered much better in the ActionRPG campaign.

Not a good intro anymore.

Use this one instead: 
https://www.youtube.com/watch?v=HvPTSZl2WCc&list=PLda3VoSoc_TSBBOBYwcmlamF1UrjVtccZ&index=9

**Comment by tylerecouture** [comment]
@fjbagley If you are still using the old one, this is much better, newer, very little coding for a great intro/first campaign.

I've got NOT Waiting for Godot badge as a prerequisite currently, so existing students who just did the old platformer won't get it, it would be way to easy for them.  I'll probably remove that before the next quarter.

Campaign Map: https://hackerspace.bytedeck.com/maps/26/1742/20/
First: https://hackerspace.bytedeck.com/quests/1680/
Last: https://hackerspace.bytedeck.com/quests/1915/

**Comment by fjbagley** [comment]
Fantastic new series. This is a much needed replacement for that original one. Glad that they have some quality content created for the 2D designers!

**Comment by tylerecouture** [comment]
@fjbagley I've updated this campaign quite a bit, including a part2 as the guy has started coming out with more videos in the series:
https://hackerspace.bytedeck.com/maps/64/

![image](https://user-images.githubusercontent.com/10604391/178120297-2d2268e0-71ab-40d7-abba-7ce3dff8faec.png)
