### ISSUE TITLE
Godot 3D Top Down Shooter

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace-todo#202]
https://www.youtube.com/playlist?list=PLaGRTLvEbVzyUMwjUPgrreyRE3AY8jhOK

**Comment by fjbagley** [comment]
Awesome! That must have taken quite some time. I look forward to seeing more of it.

**Comment by tylerecouture** [comment]
https://hackerspace.bytedeck.com/maps/49/116/64/

285 XP added to the Game Design course with just this campaign!
