### ISSUE TITLE
GIMP Wanted Poster Video Gone

### ISSUE THREAD

**Issue by fjbagley** [timberline-secondary/hackerspace-todo#205]
@tylerecouture Can you bring it back, please?
[Link](https://hackerspace.bytedeck.com/quests/150/)

**Comment by tylerecouture** [comment]
Don't know where the original went, but here's a replacement:
https://www.youtube.com/watch?v=wNMa0UPzFVs

**Comment by fjbagley** [comment]
Thanks! I had thought it was one of your videos. That's why I was asking you to bring it back.
