### ISSUE TITLE
Update Codecademy to Python 3

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace-todo#224]
It's now free:
https://www.codecademy.com/catalog/language/python
https://www.codecademy.com/learn/learn-intermediate-python-3

**Comment by fjbagley** [comment]
Great news!

**Comment by fjbagley** [comment]
Looks like they are being tricky. Only the first two lessons are free :(. Cost is $149.99 per year.

**Comment by tylerecouture** [comment]
😭
