### ISSUE TITLE
Media Literacy Campaign XP

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace-todo#225]
It's too high and now that have a few years of data can check 75%ile

**Comment by fjbagley** [comment]
Here is what I got for the 75th percentile.

1.	20 – 3XP
2.	26 – 5XP
3.	24 - 4XP
4.	24 – 4XP
5.	23 – 4XP
6.	28 – 5XP
7.	26 – 4XP
8.	24 – 4XP
9.	40 – 7XP??
10.	19 – 3XP
11.	14 – 3XP
12.	22 – 4XP

Thoughts?

**Comment by tylerecouture** [comment]
I added mine beside yours to compare.  Mostly similar. I think the XP settings you list are good.

1     20 – 3XP / 25m
2     26 – 5XP / 24m
3     24 - 4XP / 20m
4     24 – 4XP / 20m
5     23 – 4XP / 18m
6     28 – 5XP / 22m
7     26 – 4XP / 20m
8     24 – 4XP / 21m
9     40 – 7XP?? / 22m (but 57% return rate)
10     19 – 3XP / 17m
11     14 – 3XP / 17m
12     22 – 4XP / 21m
