### ISSUE TITLE
Udacity - OOP Python lessons no longer available

### ISSUE THREAD

**Issue by fjbagley** [timberline-secondary/hackerspace-todo#228]
[Lessons no longer exist](https://classroom.udacity.com/courses/ud036)

Possible alternatives (more research required):

- [Data Camp](https://www.datacamp.com/courses/object-oriented-programming-in-python)
- [Udemy](https://www.udemy.com/course/object-oriented-python-programming/)

**Comment by tylerecouture** [comment]
I still have access to it for some reason, so I've started repairing the quests by pasting the content and vids directly into the quests.

**Comment by fjbagley** [comment]
Maybe you signed up for the course so can still access it? When I click the link other lessons show up and not the OOP. OOP is no longer listed on the site. I will use your updates on my site. Thansk!

**Comment by tylerecouture** [comment]
Python OOP 3, 2, and 1 updated: 
https://hackerspace.bytedeck.com/quests/1127/

**Comment by tylerecouture** [comment]
All updated.  1-8.  https://hackerspace.bytedeck.com/quests/1133/
