### ISSUE TITLE
HackerSpace React Map Generation Required 

### ISSUE THREAD

**Issue by fjbagley** [timberline-secondary/hackerspace-todo#229]
Looks like you are missing a map:

https://hackerspace.bytedeck.com/maps/26/1726/67/

**Comment by tylerecouture** [comment]
I don't understand. What map is it? Where is this link from?

**Comment by fjbagley** [comment]
Your site. The map for React does not exist. Web Development III.

![image](https://github.com/timberline-secondary/hackerspace-todo/assets/37415548/fd69a995-ef76-411e-bc06-737242488279)

**Comment by tylerecouture** [comment]
Thanks!  That is a series Matt made that I haven't screened yet.  I fixed the map but will probably hide the series.  I think students need some vanilla JS dom manipulation before jumping into React.
