### ISSUE TITLE
Godot 4 Heartbeast simple space shooter

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace-todo#234]
This guy is A+ content. Same guy who does the Action RPG

https://www.youtube.com/playlist?list=PL9FzW-m48fn09w6j8NowI_pSBVcsb3V78

**Comment by tylerecouture** [comment]
Been sick the past few days so started working on this.  Despite him saying it is for beginners, it is not for absolute beginners and uses many advanced techniques, so I've placed it after the Gal Godot talent:
https://hackerspace.bytedeck.com/quests/campaigns/227/

I'll continue to build as new episodes are published, so it should be done in a few weeks.

**Comment by tylerecouture** [comment]
Complete!
https://hackerspace.bytedeck.com/quests/campaigns/227/

**Comment by fjbagley** [comment]
Awesome! Thanks for posting.
