### ISSUE TITLE
On Assignment - Intermediate series

### ISSUE THREAD

**Issue by mizzgoldberg** [timberline-secondary/hackerspace-todo#32]
- Underneath
- Upside Down
- New / Old
- Black & White
- Architecture

**Comment by mizzgoldberg** [comment]
More ideas: 
- empty space
- lost objects

**Comment by mizzgoldberg** [comment]
More ideas:
- feet, shoes, legs etc weird things that would look cool in a photograph

**Comment by mizzgoldberg** [comment]
- Forgotten

**Comment by mizzgoldberg** [comment]
eyes
hidden
average objects made to look cool
abstracts
black and white photography - i.e. filters
other filters
patterns in nature (different than human-made patterns quest)
portrait (would need a series of rules for photographer and subject - not public on Flickr, permission form; subject gets small amount of XP, cannot be pulled from another class, etc.

**Comment by mizzgoldberg** [comment]
Glass: Glass can be reflective, react to light, and distort images when you look through it.

**Comment by mizzgoldberg** [comment]
Patterns
Textures

**Comment by mizzgoldberg** [comment]
Black and white video (excellent!!): https://www.youtube.com/watch?v=3CiLTW2wg-Y

**Comment by mizzgoldberg** [comment]
Patterns, shapes, textures in nature: https://hackerspace.bytedeck.com/quests/submission/90774/

**Comment by tylerecouture** [comment]
Retiring old photo stuff.
