### ISSUE TITLE
Composition II

### ISSUE THREAD

**Issue by mizzgoldberg** [timberline-secondary/hackerspace-todo#33]
- Split Shapes, Patterns, Textures into 3 (Shapes required)
- Negative space - better video, proper assignment
- New quests e.g. diagonals
- Final quest required for badge with Camera Mastery

**Comment by mizzgoldberg** [comment]
Re-named "shapes" etc as "graphic elements"
Patterns, Textures to be moved to On Assignment Intermediate
Monitor XP and expectations (10/15)
Need to have some cohesion with this campaign. Should lighting be separate?

**Comment by tylerecouture** [comment]
Retiring old photo stuff.
