### ISSUE TITLE
Crash Course Games

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace-todo#35]
https://www.youtube.com/watch?v=FVTNtlq3-44&list=PL8dPuuaLjXtPTrc_yg73RghJEOdobAplG&index=2&t=0s

**Comment by tylerecouture** [comment]
https://hackerspace.sd72.bc.ca/quests/1508/

**Comment by tylerecouture** [comment]
Almost done.  Want to add a few more out of order, maybe a part2?
11 Casual Gaming
12 MMORPGs
20 PC Gaming
21 VR
22 Open Worlds Games
23 Handheld
24 Input Devices (?)
28 Pokemon (?)
30 The Future of Gaming

**Comment by tylerecouture** [comment]
Talent info added.

**Comment by fjbagley** [comment]
This has been a great campaign. Students really enjoy part 1!

**Comment by tylerecouture** [comment]
@fjbagley  This is now completed.  If you want to use the new stuff, maybe give it a week or two as that's when majority of typos, XP values, other issues get sorted out in new Campaigns and I have 3 blocks right now.

22 Quests total:
https://hackerspace.bytedeck.com/quests/campaigns/160/
