### ISSUE TITLE
Crash Course "Navigating Digital Info" 

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace-todo#36]
https://www.youtube.com/watch?v=L4aNmdL3Hr0&list=PL8dPuuaLjXtN07XYqqWSKpPrtNDiCHTzU&index=1

Maybe a better name?

Crash Course Fact Checking?
Crash Course Fake News?

**Comment by tylerecouture** [comment]
Need more examples of fake/out of context photos and video for this quest: https://hackerspace.sd72.bc.ca/quests/1526/

**Comment by tylerecouture** [comment]
More samples for additional tasks (picture, video and info verification):
http://archive.md/Kvhie
https://gizmodo.com/7-more-viral-photos-that-are-totally-fake-1832556628
https://twitter.com/najahtaa/status/861320374834909185?s=09
https://youtu.be/wj09CEW3KBY
https://twitter.com/mod_russia/status/930472894454517760?s=09

https://www.instagram.com/p/B1eBsWDlfF1/?utm_source=ig_embed&ig_mid=75849E2C-1E8D-4893-9EA6-6DA79DB0D168

**Comment by tylerecouture** [comment]
https://www.snopes.com/fact-check/bill-gates-5000-giveaway/

**Comment by tylerecouture** [comment]
![image](https://user-images.githubusercontent.com/10604391/70118695-7b7eed80-161d-11ea-80ed-8d331ed397e9.png)

**Comment by tylerecouture** [comment]
https://www.kansascity.com/latest-news/8bqlwe/picture210662664/alternates/FREE_1140/VisitKC%2025%20million%20visitors%20anally%20prank%20sign

**Comment by tylerecouture** [comment]
Consider adding to  quest 5 : https://hackerspace.sd72.bc.ca/quests/1524/

**Comment by tylerecouture** [comment]
@fjbagley finished this one a while ago.  One of my favorite generic campaigns relevant to every student:
https://hackerspace.bytedeck.com/maps/39/
https://hackerspace.bytedeck.com/quests/1531/

**Comment by fjbagley** [comment]
Thanks! I have this, but had it set to amateur instead of apprentice. I have moved it over as it is good to spread these quests out.
