### ISSUE TITLE
Creative Commons

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace-todo#49]
Stuff/links/websites have changed and this old quest needs to be updated:
https://hackerspace.sd72.bc.ca/quests/5/

**Comment by mizzgoldberg** [comment]
Only change I can see is the CC search page, which is visually different than in the video where you search for asparagus.

**Comment by mizzgoldberg** [comment]
I changed the written instructions to reflect new search page.

**Comment by tylerecouture** [comment]
Video/Gif updated now too.
