### ISSUE TITLE
Barber Logo - Why 15 XP?  

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace-todo#51]
Seems too high, should be 10?
https://hackerspace.sd72.bc.ca/quests/submission/84739/

**Comment by tylerecouture** [comment]
- [ ] https://hackerspace.sd72.bc.ca/quests/submission/85506/ - drop to 2 XP

**Comment by fjbagley** [comment]
Thanks for the heads up! Changed in ST

**Comment by mizzgoldberg** [comment]
Changed on Hackerspace too
