### ISSUE TITLE
Computers and Internet works campaigns

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace-todo#57]
- [x] https://hackerspace.sd72.bc.ca/quests/submission/85506/ - drop to 2 XP?
- [ ] https://hackerspace.sd72.bc.ca/quests/761/ drop to 2 XP
- [x] https://hackerspace.sd72.bc.ca/quests/762/ drop to 4 or 3XP
- [x] https://hackerspace.sd72.bc.ca/quests/767/ review this entire little campaign.  XP is too high.  Maybe combine the computer quest and the internet quests together into one campaign?

**Comment by mizzgoldberg** [comment]
All quests reviewed, and XP reduced for all. I like having them separate.
