### ISSUE TITLE
Blender Lego quest update

### ISSUE THREAD

**Issue by mizzgoldberg** [timberline-secondary/hackerspace-todo#65]
Izaak's feedback (diff btwn 2.79 / 2.81): A lot of the key binds have been moved from blender 2.79 to blender 2.81 mantaflow (such as the settings on the bottom being moved to the top and being mixed up into better, but different places.) Render layers have been completely changed to be associated with groups into a new setting called collections ( render layers still exist but have been moved and are a lot less friendly to use, so I just used collections.) The way that the instructor made the animation of the blocks being built up did not work, so I had to use a completely different method using a build modifier and reversing it. There are many other subtle changed which required a two minute google search but they're not too drastic to mention. Mantaflow is a completely different fluid engine, with a lot of the settings being changed, renamed or gotten rid of and new setting being added.
https://hackerspace.sd72.bc.ca/quests/submission/85912/

**Comment by tylerecouture** [comment]
This and all the other old 2.7 quests are now grouped into their own campaign, and students can download 2.7 if they want to try them.  How do get 2.7 instructions is included in the intro:
https://hackerspace.bytedeck.com/quests/315/
