### ISSUE TITLE
Typing quest

### ISSUE THREAD

**Issue by mizzgoldberg** [timberline-secondary/hackerspace-todo#72]
Change to 15 minutes a day and 3 xp?
Fits better as a supplement to doing a 10xp quest (50-60 min) in a single 75 min class.
Will not generate enough XP to pass the course (or be used to primarily pass the course).
Daily practice important for those who are actually interested in improving their typing skills and speed.

**Comment by tylerecouture** [comment]
Explain Typing badges in the typing quest, and how to get them (10fastfingers.com)

**Comment by tylerecouture** [comment]
https://hackerspace.sd72.bc.ca/quests/286/

**Comment by mizzgoldberg** [comment]
Changed to 3XP / 15 minutes.

Please review expectations re: speed. Removed inconsistent info:
Removed: "To prevent students from wasting their time on this quest where they are not improving their typing speed, it is expected that you will achieve a new high for your average typing speed at least once in every 5 times you submit this quest."
Kept: "Your Average Speed (wpm) for today must be the same or higher than your Average Speed (wpm) all time for this quest to be accepted.  If your average speed is dropping, it means either you were goofing around, or this quest is no longer useful for you to improve your typing."

Also removed: "This can be in a single class, or added up over several classes." Must be in one day.

**Comment by tylerecouture** [comment]
Talent info added.
