### ISSUE TITLE
99 numbers

### ISSUE THREAD

**Issue by mizzgoldberg** [timberline-secondary/hackerspace-todo#73]
New out-of-district students will not get a 99 number, effective immediately. 99 number being phased out district-wide for current students.
Need new way to mass-register students for computer logins at beginning of semester.
Need new way for students to log into Hackerspace website.
Probably other stuff too.

**Comment by mizzgoldberg** [comment]
Intro and course end surveys currently require 99 number.

**Comment by tylerecouture** [comment]
Everything switched to firstname.lastname
