### ISSUE TITLE
Photo Composition Intro 1 & 2

### ISSUE THREAD

**Issue by mizzgoldberg** [timberline-secondary/hackerspace-todo#74]
Comp 1: Fix. Reduce text. Make clear. Provide example. Make it 10 photos? Taken from a variety of angles & distances (near/medium/far). Goal: get students moving, taking loads of photos, and picking one favourite.
Comp 2: See above, not as many, clearly a different quest
Comp 1 inside, Comp 2 outside? Something.

**Comment by tylerecouture** [comment]
Retiring old photo stuff.
