### ISSUE TITLE
More 3D Godot campaigns

### ISSUE THREAD

**Issue by mizzgoldberg** [timberline-secondary/hackerspace-todo#75]
Like the ball thing (Godot Basics campaign) and the 3D Maze Game. Students like them.

**Comment by tylerecouture** [comment]
Gonna close this because I've added [specific campaign ideas as their own issues](https://github.com/timberline-secondary/hackerspace-todo/issues?q=is%3Aissue+label%3A%22Campaigns%3A+New%22+label%3A%22Course%3A+Game+Design%22):
