### ISSUE TITLE
GPU rendering on Blender 2.79

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace-todo#81]
![image](https://user-images.githubusercontent.com/10604391/73893038-5a10cc80-482d-11ea-9bd3-649bbb25d036.png)

Error with Blender 2.79 when trying to use GPU CUDA rendering

**Comment by fjbagley** [comment]
2.8 ;)

**Comment by tylerecouture** [comment]
Not gonna do.  Just upgrade to 2.8..
