### ISSUE TITLE
Broken link in Godot Intro

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace-todo#82]
https://hackerspace.sd72.bc.ca/quests/submission/88649/

The showcase link is broken, hopefully it comes back up? I couldn't find a suitable replacement.

**Comment by tylerecouture** [comment]
"Browse some of the games created in Godot [here](https://godotengine.org/showcase)."

**Comment by mizzgoldberg** [comment]
Could do link to YouTube showcase instead? https://www.youtube.com/watch?v=ZR1Yfmr1KRM
Not perfect, but viable temporarily? Games listed in the description:
- RivenTails: Defense, by Kivano
- Headcase, by Fracteed
- Protocorgi, by Kemeno Games
- Ex Zodiac, by Ben Hickling
- Spooky Ghosts Dot Com, by Justin Forcier
- RPG in a Box, by Justin Arnold
- Deep Sixed, by Little Red Dog Games
- Infinistate, by Fracteed
- Galactic Bulwark Strike, by Josep G. Camarasa
- Daunting Worlds, by Manuel Strey
- High Hat, by Carter Anderson
- Wallrider, by Zylann Prods
- Gun Totting Cats, by Kit9Studio
- Harmon:i:c, by AWKgamedev

**Comment by tylerecouture** [comment]
I just remove it.  There is a showcase in the BornCG vid anyway.
