### ISSUE TITLE
Inkscape Basics #1 question redundancy

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace-todo#95]
Questions 1A and 1C are basically the same thing?

https://hackerspace.sd72.bc.ca/quests/submission/89507/

**Comment by mizzgoldberg** [comment]
Same answer, different question - one when drawing, one when enlarging. Students should know to use CTRL for both (drawing perfect circle/square, and constraining proportions while enlarging). Want to change the questions so they seem more different?

**Comment by tylerecouture** [comment]
I added a couple more questions with ALT and also for rotation. I think this is fine.
